export const enum CoursesActionTypes {
	CREATE_COURSE = 'CREATE_COURSE',
	FETCH_COURSES = 'FETCH_COURSES',
	FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS',
	FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE',
	DELETE_COURSE = 'DELETE_COURSES',
	UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS',
}
