export enum TEXT_BUNDLE {
	emptyListTitle = 'Your List Is Empty',
	emptyCourseListMessage = 'Please use ’Add New Course’ button to add your first course',
	inputText = 'Input text',
	description = 'Description',
	id = 'ID',
	duration = 'Duration',
	creationDate = 'Creation Date',
	created = 'Created',
	authors = 'Authors',
	registration = 'Registration',
	login = 'Login',
	courseEdit = 'Course edit/create page',
	mainInfo = 'Main Info',
	author = 'Author',
	courseAuthors = 'Course Authors',
	authorsList = 'Authors List',
	noPermissionsMessage = `You don't have permissions to create a course. Please log in as ADMIN`,
}
